---
# tasks file for sec_configuration/
- name: Check if emergency account creation is enabled
  fail:
    msg: "Emergency account creation is disabled."
  when: not emergency_account | bool

- name: Create an emergency user account
  user:
    name: "{{ emergency_username }}"
    password: "{{ emergency_password }}"
    state: present
    create_home: yes
  when: emergency_account | bool

- name: Add emergency user to sudo group
  user:
    name: "{{ emergency_username }}"
    groups: sudo
    append: yes
  when: emergency_account | bool